### ISSUE TITLE
Cannot read property 'reverse' of null

### ISSUE THREAD

**Issue by adityamr15** [AdamPflug/express-brute-memcached#1]
I got an error when using memcached for express-brute.

```
TypeError: Cannot read property 'reverse' of null
    at Client.connect (/Users/espheremac/Projects/mp-wallet-api/node_modules/memcached/lib/memcached.js:129:41)
    at Client.memcachedCommand [as command] (/Users/espheremac/Projects/mp-wallet-api/node_modules/memcached/lib/memcached.js:300:10)
    at Client.get (/Users/espheremac/Projects/mp-wallet-api/node_modules/memcached/lib/memcached.js:810:10)
    at MemcachedStore.get (/Users/espheremac/Projects/mp-wallet-api/node_modules/express-brute-memcached/index.js:22:14)
    at null.<anonymous> (/Users/espheremac/Projects/mp-wallet-api/node_modules/express-brute/index.js:82:15)
    at keyFunc (/Users/espheremac/Projects/mp-wallet-api/node_modules/express-brute/index.js:39:41)
    at null.<anonymous> (/Users/espheremac/Projects/mp-wallet-api/node_modules/express-brute/index.js:47:3)
    at Layer.handle [as handle_request] (/Users/espheremac/Projects/mp-wallet-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/espheremac/Projects/mp-wallet-api/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/espheremac/Projects/mp-wallet-api/node_modules/express/lib/router/route.js:112:3)
```

**Comment by miira** [comment]
You probably didn't set port. e.g.var store = new MemcachedStore(['127.0.0.1:11211']);
It is visible in the source code - line 129 in /memcached/lib/memcached.js 
There is regular expression checking the input and it requires the port: /(.*):(\d+){1,}$/

**Comment by reg0** [comment]
it would be good to put it in docs/readme, currently example code shows inly IP without the port, and it actually does not work

**Comment by AdamPflug** [comment]
I think this may have changed since this module originally came out. In any case, I updated the README.
